# Generated by Django 3.0.7 on 2020-06-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name"],
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
    ]
