# Generated by Django 3.0.7 on 2020-06-21 02:28

import django.core.validators
from django.db import migrations, models

import books.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0002_auto_20200621_0220"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "edition",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ]
                    ),
                ),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1500),
                            books.validators.max_value_year_validation,
                        ]
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="authors.Author"
                    ),
                ),
            ],
        ),
    ]
