# Generated by Django 3.0.7 on 2020-06-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("name", "edition", "publication_year")},
        ),
    ]
